// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUfl825MzbcQF08dIbvuGTRHX5HZ6Cd8I',
    appId: '1:979647142707:web:97068062a8011a143f7c46',
    messagingSenderId: '979647142707',
    projectId: 'stemtutor-4cdc5',
    authDomain: 'stemtutor-4cdc5.firebaseapp.com',
    storageBucket: 'stemtutor-4cdc5.appspot.com',
    measurementId: 'G-M4V6PVF6FD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClppI071ShqRchxH8jxnLZqymICa-Z2W0',
    appId: '1:979647142707:android:a61f8f47b2027de93f7c46',
    messagingSenderId: '979647142707',
    projectId: 'stemtutor-4cdc5',
    storageBucket: 'stemtutor-4cdc5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlpln2V7xOOLxbybKSYSnn2qCjnkoiSc0',
    appId: '1:979647142707:ios:bf696f2a344f632b3f7c46',
    messagingSenderId: '979647142707',
    projectId: 'stemtutor-4cdc5',
    storageBucket: 'stemtutor-4cdc5.appspot.com',
    iosBundleId: 'com.example.stemTutorFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlpln2V7xOOLxbybKSYSnn2qCjnkoiSc0',
    appId: '1:979647142707:ios:bf696f2a344f632b3f7c46',
    messagingSenderId: '979647142707',
    projectId: 'stemtutor-4cdc5',
    storageBucket: 'stemtutor-4cdc5.appspot.com',
    iosBundleId: 'com.example.stemTutorFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUfl825MzbcQF08dIbvuGTRHX5HZ6Cd8I',
    appId: '1:979647142707:web:d635a71c3f4608da3f7c46',
    messagingSenderId: '979647142707',
    projectId: 'stemtutor-4cdc5',
    authDomain: 'stemtutor-4cdc5.firebaseapp.com',
    storageBucket: 'stemtutor-4cdc5.appspot.com',
    measurementId: 'G-YDM1M8K51D',
  );

}